- name: check OS distribution
  fail: msg="Sorry. the playbook can only on Centos7 or Centos8."
  when: 
    - ( ansible_distribution != 'CentOS' ) or
      ( ansible_distribution_major_version != '8' )

- name: include CentOS8 yml
  include_vars:
    file: centos8.yml
  when: ansible_distribution_major_version == '8'

